version: '3'
services:
  madb:
    image: mysql/mysql-server:5.7
    container_name: mysql-serv
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'mydatabases'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    
    volumes:
      - ma-base:/var/lib/mysql

    ports:
      - 127.0.0.1:3306:3306
    expose:
      - 3306
  myappserver:
    build: .
    image: miniapp
    container_name: miniappserver
    restart: always
    links:
      - madb:madb
    environment:
      - DATABASE_HOST=madb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mydatabases
      - DATABASE_PORT=3306
    ports : 
      - 8000:8000
    command: mvn clean spring-boot:run
    depends_on:
      - madb
volumes:
  ma-base:
    driver: local