version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'mydatabases'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    
    volumes:
      - ma-base:/var/lib/mysql

    ports:
      - 127.0.0.1:3306:3306
    expose:
      - 3306
  myserver:
    build: .
    image: miniapp
    container_name: miniappserver
    restart: always
    links:
      - db:db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mydatabases
      - DATABASE_PORT=3306
    depends_on:
      - db
    ports : 
      - 8000:8000
   
volumes:
  ma-base:
    driver: local