version: '3'
services:
  mysql:
    container_name: mysqlServer
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: mydatabases
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
    - "127.0.0.1:3306:3306"
    restart: always
    volumes:
    - /var/lib/mysql-data:/var/lib/mysql
  myvuejs:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8000:8000
    command: mvn clean spring-boot:run
    depends_on:
    - mysql